name: 'PNPM install'
description: 'Run pnpm install with cache enabled'

runs:
  strategy:
    matrix:
      node-version: [20]

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline
