export {
  PaginationComponent,
  paginationDefaultValueProvider,
  FLOWBITE_PAGINATION_CURRENT_PAGE_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_BUTTON_PROPERTIES_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_CUSTOM_STYLE_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_PREVIOUS_ICON_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_NEXT_ICON_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_FIRST_ICON_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_LAST_ICON_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_TABS_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_PAGE_SIZE_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_HAS_FIRST_LAST_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_HAS_PREV_NEXT_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_NAVIGATION_MODE_DEFAULT_VALUE,
  FLOWBITE_PAGINATION_SIZE_DEFAULT_VALUE,
} from './pagination.component';
export type { PaginationProperties, PaginationClass, PaginationTheme } from './pagination.theme';
export { paginationTheme } from './pagination.theme';
export {
  PaginationThemeService,
  FLOWBITE_PAGINATION_THEME_TOKEN,
} from './pagination.theme.service';
