name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Start the release with dryRun parameter'
        required: true
        type: boolean
        default: true

jobs:
  release:
    name: Release new version 🛠
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write
    steps:
      - name: Check out the code 🗄
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup NodeJS 💿
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Monorepo install
        uses: ./.github/actions/setup

      - name: Release new version 🛠
        run: pnpm lib:release -- --ci --verbose --skip-nx-cache --dryRyn=${{ github.event.inputs.dryRun }}
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
