name: Release

on:
  workflow_dispatch:
  pull_request:

jobs:
  release:
    name: Release new version 🛠
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Check out the code 🗄
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS 💿
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Monorepo install
        uses: ./.github/actions/setup

      - name: Release new version 🛠
        run: pnpm lib:release -- --ci --verbose --skip-nx-cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
