name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the version'
        required: false
        type: string
      dryRun:
        description: 'Start the release with dryRun parameter'
        required: true
        type: boolean
        default: true

jobs:
  release:
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/release') || (github.event_name == 'workflow_dispatch' && github.event.inputs.dryRun == 'true')
    name: Release new version 🛠
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Check out the code 🗄
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Monorepo install
        uses: ./.github/actions/setup

      - name: Release new version 🛠
        run: pnpm exec nx release {{ github.event.inputs.version || '' }} --verbose --dryRun=${{ github.event.inputs.dryRun }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
